### ISSUE TITLE
Hugo New Problem

### ISSUE THREAD

**Issue by AngangGuo** [1v0dev/hugo-intellij-plugin#2] opened 2020-05-06 22:30 UTC
The content of  my `archetypes/default.md` is as following:
```
---
title: "{{ replace .Name "-" " " | title }}"
date: {{ .Date }}
tags: []
draft: true
---
```

If I run `hugo new blog/fourth.md` from command line, the front matter is exactly the same as the content in `archetypes/default.md`.

But if I right click on the `content` folder in Goland and select `Hugo New` > `blog/third.md`. The front matter of the `third.md` is as following:
```
---
title: "Thrid"
date: 2020-05-06T15:18:10-07:00
draft: true
---
```

The `tags: []` line is missing. Which means it doesn't read the content of the `archetypes/default.md`.

Can you please fix it?

**Comment by 1v0dev** [comment] 2020-05-17 21:15
I did some testing. For me the archetypes worked but the changes I made to them were not recognized by Hugo new.Looks like the IDE does not save the archetype file immediately after editing it, so running the new command used the previous version. I added invoking the 'Save All' command before running 'new' command so it should operate on the latest version of the archetype. The update is already published and awaiting JetBrains approval. Please let me know if that solves your problem.

**Comment by AngangGuo** [comment] 2020-05-30 17:23
Sorry, after I update the plugin, when I type the file name in the Hugo New and press enter, nothing happens. It doesn't create any document.

**Comment by 1v0dev** [comment] 2021-02-19 14:27
I can't reproduce that issue and no other users submitted such feedback. I am closing the issue.

**Closed as completed by 1v0dev** 2021-02-19 14:27 UTC
